### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by F-alling** [JetStarfish-Modding/jets_better_exploration#1]
please i want to build it myself

**Comment by hugeblank** [comment]
I'd recommend watching a fabric modding tutorial or something, as the method for building is no different from any other mod.

`./gradlew build` if on linux, and `gradlew.bat build` if on windows. Or if using an IDE like IDEA there should be a gradle tab where you'll find a "build" button. Output will be in `build/libs`. Please note that the license for this version of the mod is All Rights Reserved, meaning that redistribution is technically not permitted. There's plans to re-license the mod to allow for it, but for now please don't. Building for your own personal enjoyment is OK, though.
