### ISSUE TITLE
A backport to 1.20.1 maybe

### ISSUE THREAD

**Issue by f24816** [JetStarfish-Modding/jets_better_exploration#6]

**Comment by hugeblank** [comment]
It was finished 30 minutes before you posted this:
https://github.com/JetStarfish-Modding/jets_better_exploration/tree/1.20.1
Please look forward to a proper release when I get the go-ahead from jet, or feel free to build it from source if you have the resources.

**Comment by leftbones** [comment]
@hugeblank Any word on an official release for this yet?

**Comment by Rebel459** [comment]
@leftbones you can just build the 1.20.1 version of the mod here from source, just use the slightly older commit from when it was under MIT and you'll be fine
the dev also has the jar uploaded officially on the patreon page, both options work
